using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Estacionamento.Api.Migrations
{
    /// <inheritdoc />
    public partial class AdicionaLogAtividade : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""LogsAtividade"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""DataHora"" timestamp without time zone NOT NULL,
                    ""AdminId"" integer,
                    ""AdminUsuario"" character varying(50),
                    ""Acao"" character varying(50) NOT NULL,
                    ""Entidade"" character varying(50),
                    ""EntidadeId"" integer,
                    ""Detalhes"" character varying(500) NOT NULL,
                    ""Sucesso"" boolean NOT NULL,
                    ""Origem"" character varying(30) NOT NULL,
                    CONSTRAINT ""PK_LogsAtividade"" PRIMARY KEY (""Id"")
                );
                CREATE INDEX IF NOT EXISTS ""IX_LogsAtividade_Acao"" ON ""LogsAtividade"" (""Acao"");
                CREATE INDEX IF NOT EXISTS ""IX_LogsAtividade_DataHora"" ON ""LogsAtividade"" (""DataHora"");
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "LogsAtividade");
        }
    }
}
